# Site settings
title: Vignesh Aiyer
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Vignesh Aiyer
user_description: Experienced Salesforce Developer with a demonstrated history of working in the financial industry. I am passionate about understanding complex systems and delivering clean, test-covered, well-designed, scalable code to make the systems interact with ease.
user_title: Software Engineer
email: vikyaiyer1997@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
